{{- if .Values.secrets.create -}}
# ---------------------------------------------------------
# Secret Template for Database Service (Only for Reference)
# ---------------------------------------------------------

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  # The key name is configurable via values.yaml for flexibility.
  {{ .Values.secret.key }}: {{ .Values.secret.value | quote }}
{{- end -}}