apiVersion: v1
kind: Config
clusters:
  - name: name_placeholder
    cluster:
      certificate-authority-data: ca_data_placeholder
      server: server_placeholder
users:
  - name: user_name_placeholder
    user:
      token: user_token_placeholder
contexts:
  - name: context_name_placeholder
    context:
      cluster: context_cluster_placeholder
      namespace: context_ns_placeholder
      user: context_user_placeholder
current-context: current_context_placeholder
