{{- if .Values.networkPolicy.enabled -}}
# ------------------------------------------------------------------------------------
# Network Policy for the Postgres Database - allows incoming requests from API-Service
# ------------------------------------------------------------------------------------

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  # This policy applies to all pods created by postgres-service StatefulSet.
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  
  policyTypes:
  - Ingress

  # Ingress rule to update the inbound rule for database connection.
  ingress:
  - from:
    # This rule allows connections FROM pods that match these labels.
    - podSelector:
        matchLabels:
          # The labels are taken from the values.yaml file.
          {{- toYaml .Values.networkPolicy.ingress.fromApiService.podSelector | nindent 10 }}
    ports:
    # The connection is only allowed on the specified PostgreSQL port.
    - protocol: TCP
      port: {{ .Values.service.port }}
{{- end -}}
