# --------------------------------------
# Configmap for mounting redis.conf data
# --------------------------------------

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  # The configuration file content
  redis.conf: |
    # Redis configuration file
    protected-mode yes
    bind 0.0.0.0
    port 6379
    requirepass password-placeholder
    appendonly yes
    appendfsync everysec
    dir /data
    loglevel verbose
    logfile ""
